# Generated by Django 5.0.2 on 2025-05-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_evento', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('publico', models.TextField(blank=True, max_length=255, null=True)),
                ('programa', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('cupo_max', models.CharField(blank=True, max_length=255, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
