# Generated by Django 5.0.2 on 2025-05-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0004_eventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
